### ISSUE TITLE
KInputImage: Allow cropping before upload

### ISSUE THREAD

**Issue by tmjoen** [brandocms/brando#345]
https://norserium.github.io/vue-advanced-cropper/

**Comment by tmjoen** [comment]
https://github.com/Norserium/vue-advanced-cropper/issues/41 :eyes:

**Comment by Norserium** [comment]
@tmjoen I have seen that you mentioned the issue about the increasing of image file size. 

It's not the concern of the library, but anyway I updated the upload example and it should almost completely resolve the mentioned issue.

**Comment by tmjoen** [comment]
> @tmjoen I have seen that you mentioned the issue about the increasing of image file size.
> 
> It's not the concern of the library, but anyway I updated the upload example and it should almost completely resolve the mentioned issue.

Thanks for following up — your library looks amazing!
